---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: go-web-app
  template:
    metadata:
      labels:
        name: go-web-app
    spec:
      containers:
      - name: application
        image: test:latest
        # imagePullPolicy: IfNotPresent
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: go-web-config
        ports:
          - containerPort: 8080
        volumeMounts:
        - name: tz-application
          mountPath: /etc/localtime
      volumes:
      - name: tz-application
        hostPath:
          path: /usr/share/zoneinfo/Asia/Kolkata